a = int(input("Enter the 1st number: "))
b = int(input("Enter the 2nd number: "))
print(f"Addition is {a+b}")
print(f"Subtraction is {a-b}")
print(f"Multiplication is {a*b}")
print(f"Division is {a/b}")